### ISSUE TITLE
gzip.BadGzipFile: Not a gzipped file (b'(\xb5')

### ISSUE THREAD

**Issue by Yileri** [hpsec/lacat#8]
Hello, when I try to process my arcsight files, I am getting "gzip.BadGzipFile: Not a gzipped file (b'(\xb5')" error. It seems like the script does not recognize the chunk as gzipped but I am pretty sure it is. What could be the issue?

Traceback (most recent call last):
  File "C:\Users\HP2\PycharmProjects\lacat\main.py", line 321, in <module>
    dump_cef(events, to_json=options.json, limit_to=options.filter)
  File "C:\Users\HP2\PycharmProjects\lacat\main.py", line 163, in dump_cef
    for c in cef_recs:
  File "C:\Users\HP2\PycharmProjects\lacat\main.py", line 235, in read_cef
    for event in parse_chunk(chunk, event_count):
  File "C:\Users\HP2\PycharmProjects\lacat\main.py", line 145, in parse_chunk
    zero, length = struct.unpack(">hh", f.read(4))
  File "C:\Users\HP2\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 301, in read
    return self._buffer.read(size)
  File "C:\Users\HP2\AppData\Local\Programs\Python\Python310\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "C:\Users\HP2\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "C:\Users\HP2\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'(\xb5')

**Comment by mahmoudawni88** [comment]
Hi,

Have you found any solution for this issue?

Thanks,
Awni

**Comment by Yileri** [comment]
> Hi,
> 
> Have you found any solution for this issue?
> 
> Thanks, Awni

I don't have enough info but there is a new tool for Arcsight files that does this job. One of my coworkers found it in the official documentation I think

**Comment by mahmoudawni88** [comment]
Hi Yileri,

Can you share the link please?

Thanks,
Awni
